# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97f764a1e41e6011e85ede973f7f063fa669f660ac50dbeff87400c2bbcd11f1e994c15d05e1cdb7e6f9e3d55c0ef16e5ecf4e614c850289d8e54ee186e6f42a

test:
  secret_key_base: c6bce286e6378729c4901efa7460ff0ee16422d41718376fb4dfe878a2e53e07a5f219fb4071b189485e5a494150ce987261703c6df86b0c3417a80fa39a6716

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
